[deploy]
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[services]

[services.backend]
source = "backend"
icon = "fastapi"
variables = [
  "DATABASE_URL=${{Postgres.DATABASE_URL}}",
  "REDIS_URL=${{Redis.REDIS_URL}}",
  "PORT=8000",
  "ENVIRONMENT=production"
]

[services.frontend]
source = "frontend"
icon = "angular"
variables = [
  "VITE_API_URL=${{backend.RAILWAY_PUBLIC_DOMAIN}}",
  "PORT=3000"
]
buildCommand = "npm run build"
startCommand = "npm run start"

[services.Postgres]
icon = "postgres"

[services.Redis]
icon = "redis"